services:
#  backend:
#    image: tolog_backend
#    restart: always
#    ports:
#      - "8080:8080"
#    build:
#      context: .
#    container_name: ToLog
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/log_db
#      SPRING_DATASOURCE_USERNAME: log
#      SPRING_DATASOURCE_PASSWORD: T0l@gU$e&&1
#    depends_on:
#      - broker
#      - db

  logdb:
    image: postgres:17
    container_name: logdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=log
      - POSTGRES_PASSWORD=t0l0g
      - POSTGRES_DB=log_db
  broker:
    image: apache/kafka:latest
    container_name: broker
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    
