spring:
  application:
    name: TOlogUseLOG
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: swiss18
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true