spring:
  application:
    name: TOlogUseLOG
  datasource:
    url: jdbc:postgresql://localhost:5433/log_db
    username: log
    password: t0l0g
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jobrunr:
  background-job-server:
    poll-interval-in-seconds: 5
    worker-count: 4
    enabled: true
  dashboard:
    enabled : true
    port: 8000
  database:
    skip-create: false

logging:
  file:
    name: springLog

server:
  address: 0.0.0.0
  port: 8080

bot:
  url:
    address: localhost
    port: 3000
    post: http://${bot.url.address}:${bot.url.port}/sendMessage