spring:
  application:
    name: TOlogUseLOG
  datasource:
    url: jdbc:postgresql://localhost:5432/log
    username: postgres
    password: swiss18
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  address: 0.0.0.0
  port: 8080

bot:
  url:
    post: "0.0.0.0:3000"